from __future__ import annotations

from pathlib import Path

import duckdb
import pandas as pd
import streamlit as st
import altair as alt


st.set_page_config(page_title="City Rides Data Platform", layout="wide")

DATA_PATH = Path("data/warehouse.duckdb")

st.title("City Rides Data Platform Dashboard")
st.caption("Explore hourly trip metrics generated by the pipeline.")

if not DATA_PATH.exists():
    st.warning("Warehouse not found. Run the pipeline first to generate data.")
    st.stop()

@st.cache_data(ttl=300)
def load_hourly_metrics() -> pd.DataFrame:
    con = duckdb.connect(str(DATA_PATH), read_only=True)
    try:
        df = con.execute(
            """
            SELECT
              pickup_date,
              pickup_hour,
              zone_id,
              trip_count,
              avg_trip_distance,
              avg_fare_amount,
              total_revenue
            FROM fct_trip_hourly
            ORDER BY pickup_date, pickup_hour
            """
        ).df()
    finally:
        con.close()

    df["pickup_date"] = pd.to_datetime(df["pickup_date"])
    return df


@st.cache_data(ttl=300)
def load_pipeline_runs() -> pd.DataFrame:
    con = duckdb.connect(str(DATA_PATH), read_only=True)
    try:
        table_exists = con.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_name = 'pipeline_runs'
            """
        ).fetchone()[0]
        if not table_exists:
            return pd.DataFrame()

        return con.execute(
            """
            SELECT
              run_id,
              source_name,
              status,
              started_at,
              duration_seconds,
              bronze_rows,
              silver_rows,
              gold_rows,
              quality_passed
            FROM pipeline_runs
            ORDER BY started_at DESC
            LIMIT 10
            """
        ).df()
    finally:
        con.close()


df = load_hourly_metrics()
pipeline_runs = load_pipeline_runs()

col1, col2, col3 = st.columns(3)
col1.metric("Total Trips", f"{df['trip_count'].sum():,}")
col2.metric("Total Revenue", f"${df['total_revenue'].sum():,.2f}")
col3.metric("Avg Fare", f"${df['avg_fare_amount'].mean():.2f}")

if not pipeline_runs.empty:
    latest_run = pipeline_runs.iloc[0]
    st.caption(
        f"Latest run `{latest_run['run_id']}` from `{latest_run['source_name']}` finished with status `{latest_run['status']}` "
        f"and loaded {int(latest_run['silver_rows']):,} cleaned trips."
    )

st.subheader("Trips Over Time")
chart = (
    alt.Chart(df)
    .mark_line()
    .encode(
        x=alt.X("pickup_date:T", title="Pickup Date"),
        y=alt.Y("trip_count:Q", title="Trips"),
        color=alt.Color("zone_id:N", legend=None),
        tooltip=["pickup_date:T", "pickup_hour:Q", "zone_id:N", "trip_count:Q"],
    )
)

st.altair_chart(chart, use_container_width=True)

st.subheader("Sample Data")
st.dataframe(df.head(50), use_container_width=True)

if not pipeline_runs.empty:
    st.subheader("Pipeline Runs")
    st.dataframe(pipeline_runs, use_container_width=True)
